### PR TITLE
Add index.js file

### PR DESCRIPTION
**Pull request by frostney**
With this change, the module can be imported with `import Composer from 'react-native-message-composer'` instead needing to require `NativeModules` by yourself in application code.

### CODE REVIEW

**Comment by anarchicknight** [comment]
will hopefully get a chance to look at this on the weekend

**Comment by anarchicknight** [comment]
with this change I think you would need to update the usage instructions again from your last PR?

If you could confirm and action if this is the case and include on this PR then we can look at merging it in

Thanks

**Comment by frostney** [comment]
Yes, the usage instructions instructions would need to be update. I'll get right on that.

**Comment by keplersj** [comment]
I just found this project and this PR would be super helpful. So, sorry for this but - ___bump___.

**Comment by anarchicknight** [comment]
this has now been added in 0.1.0

**Comment by keplersj** [comment]
Thank you!

**Pull request closed without merging**
